### ISSUE TITLE
Unit of Leibovici and Altieri Entropy

### ISSUE THREAD

**Issue by le000043** [Mr-Milk/SpatialEntropy#1]
Hello,

What is the unit of  Leibovici or Altieri Entropy in your example?
Does either Leibovici or Altieri Entropy involve normalization in their calculation?

Thank you so much

**Comment by Mr-Milk** [comment]
There is no unit like meters or seconds in entropy, if you look at the equation it's actually probability. 

Neither involves normalization.

**Comment by le000043** [comment]
Thank you for your response. If it is probability then how would I interpret a value that is greater than 1.0?

**Comment by Mr-Milk** [comment]
I mean it’s based on probability hence no unit, but the value itself is not probability. Spatial entropy is also based on Shannon entropy, except that the events are spatial co-occurrences.
