### ISSUE TITLE
Missing adj_matrix

### ISSUE THREAD

**Issue by MichaelMMeskhi** [Mr-Milk/SpatialEntropy#4]
One of the examples in the `readme` has `e.adj_matrix` which returns an error as the altieri class only returns `residue`, `mutual_info`, and `entropy`. Might want to add `adj_matrix` as well.

**Comment by Mr-Milk** [comment]
Ok, I will add something like `scipy.spatial.distance.pdist` but not `adj_matrix`, it consumes too much RAM if you have lots of points.

**Comment by MichaelMMeskhi** [comment]
Yeah that's understandable.
