### ISSUE TITLE
Global Spatial Info

### ISSUE THREAD

**Issue by MichaelMMeskhi** [Mr-Milk/SpatialEntropy#5]
Quick question, in Altieri's paper it is mentioned that 

> Indeed, the global values of the two components of spatial entropy, i.e. spatial mutual information and spatial residual entropy, are unaf- fected by such choice. The distance breaks are instead crucial in defining the partial terms, that determine the detail and depth of the investigation.

If I understand this correctly, same data but different windows will still have same MI(Z, W) and H(Z)w globally. But the code does not support this idea.

**Comment by CSUPC** [comment]
Do you know how to explain it? Setting different distance intervals for the same data will result in different results
