### ISSUE TITLE
Question regarding the calculation of p(w_k)

### ISSUE THREAD

**Issue by Marnellus** [Mr-Milk/SpatialEntropy#8]
Hey!

In the paper 

"Altieri, Linda; Cocchi, Daniela; Roli, Giulia (2019). Advances in spatial entropy measures. Stochastic Environmental Research and Risk Assessment, 33(4-6), 1223–1240. doi:10.1007/s00477-019-01686-y ", 

on page 1226 Altieri writes:

![image](https://user-images.githubusercontent.com/74869816/208176999-32f7c231-2180-4adf-88e0-e2f059d0fe79.png)

So p(w_k) is the the share of how many co-occurances, regardless of category z_r, fall into this interval. In your Altieri Script it's basically just their share of how much of the distance of the maximum distance they cover:

![image](https://user-images.githubusercontent.com/74869816/208178024-2dcef32d-a712-4826-8306-2a462c20e7b6.png)

I'm not familiar with the domain at all, was their a reason for this approach ?

**Comment by Mr-Milk** [comment]
Sorry, some part of this implementation is wrong, I will correct it in the future. I had a new and faster implementation in Rust, please see [spatialtis_core](https://github.com/mr-milk/spatialtis-core).
